# Generated by Django 6.0.1 on 2026-04-06 07:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0004_subscriptioninstallment_amount_paid_and_more"),
        ("payments", "0002_alter_payment_payment_method"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="installment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="payments",
                to="members.subscriptioninstallment",
            ),
        ),
    ]
