# Generated by Django 6.0.1 on 2026-04-17 04:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_gymoffice_currency_code_gymoffice_currency_symbol'),
        ('members', '0013_member_is_deleted_subscription_is_deleted'),
        ('payments', '0003_payment_installment'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Amount discounted via an offer', max_digits=10),
        ),
        migrations.CreateModel(
            name='GymOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('discount_percentage', models.DecimalField(decimal_places=2, help_text='Percentage discount to apply (e.g., 10 for 10%)', max_digits=5)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='home.gymoffice')),
                ('specific_members', models.ManyToManyField(blank=True, help_text='If empty, applies to all members of the gym', related_name='eligible_offers', to='members.member')),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.AddField(
            model_name='payment',
            name='offer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='payments.gymoffer'),
        ),
    ]
