# Generated by Django 6.0.1 on 2026-04-07 04:14

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("home", "0005_alter_licensekey_unique_together_hikconfigurationdb"),
        ("payments", "0003_payment_installment"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FinanceTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[("Income", "Income"), ("Expense", "Expense")],
                        max_length=10,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("date", models.DateField(default=django.utils.timezone.now)),
                ("description", models.CharField(max_length=500)),
                (
                    "category",
                    models.CharField(
                        blank=True,
                        help_text="e.g., 'Subscription', 'Salary', 'Equipment'",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "receipt_number",
                    models.CharField(
                        blank=True,
                        help_text="Physical or digital receipt number",
                        max_length=255,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "branch",
                    models.ForeignKey(
                        blank=True,
                        help_text="Branch associated with this transaction (if any)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="finance_transactions",
                        to="home.gymbranch",
                    ),
                ),
                (
                    "gym",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="finance_transactions",
                        to="home.gymoffice",
                    ),
                ),
                (
                    "payment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="finance_records",
                        to="payments.payment",
                    ),
                ),
                (
                    "recorded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recorded_transactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-date", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["gym", "transaction_type"],
                        name="finance_fin_gym_id_65727d_idx",
                    ),
                    models.Index(
                        fields=["branch", "transaction_type"],
                        name="finance_fin_branch__8138e9_idx",
                    ),
                    models.Index(fields=["date"], name="finance_fin_date_4c2559_idx"),
                ],
            },
        ),
    ]
