# Generated by Django 6.0.1 on 2026-04-08 06:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("home", "0005_alter_licensekey_unique_together_hikconfigurationdb"),
    ]

    operations = [
        migrations.CreateModel(
            name="EnquiryData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_created", models.DateField(auto_now_add=True)),
                ("date_updated", models.DateField(auto_now=True)),
                ("name", models.CharField(max_length=250)),
                ("phone_number", models.CharField(max_length=20)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("age", models.IntegerField(blank=True, null=True)),
                ("number_of_followup", models.IntegerField(default=0)),
                ("last_follow_up_date", models.DateField(blank=True, null=True)),
                ("next_follow_up_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("completed", "Completed"),
                            ("in_progress", "In Progress"),
                            ("not_required", "Not Required"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=30,
                    ),
                ),
                ("conversion", models.BooleanField(default=False)),
                (
                    "gym",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enquiries",
                        to="home.gymoffice",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Enquiry Data",
            },
        ),
        migrations.CreateModel(
            name="EnquiryStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_of_status", models.DateTimeField(auto_now_add=True)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("completed", "Completed"),
                            ("in_progress", "In Progress"),
                            ("not_required", "Not Required"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=30,
                    ),
                ),
                (
                    "call_status",
                    models.CharField(
                        choices=[
                            ("rnr", "RNR"),
                            ("callback", "Callback"),
                            ("interested", "Interested"),
                            ("not_interested", "Not Interested"),
                            ("converted", "Converted"),
                            ("follow_up", "Follow Up"),
                            ("closed", "Closed"),
                        ],
                        default="rnr",
                        max_length=30,
                    ),
                ),
                (
                    "enquiry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="statuses",
                        to="enquiry.enquirydata",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Enquiry Statuses",
            },
        ),
    ]
