# Generated by Django 6.0.1 on 2026-04-10 03:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiry', '0001_initial'),
        ('members', '0009_subscription_installment_period_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquirydata',
            name='converted_member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='converted_from_enquiries', to='members.member'),
        ),
    ]
