# Generated by Django 5.2.4 on 2026-01-14 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_customuser_deleted_at_customuser_is_deleted_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='licensekey',
            unique_together={('assigned_to', 'key')},
        ),
    ]
