# Generated by Django 5.2.4 on 2026-01-14 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_licensekey_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licensekey',
            name='valid_until',
            field=models.DateField(blank=True, null=True),
        ),
    ]
