# Generated by Django 6.0.1 on 2026-01-15 06:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_licensekey_valid_until'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='licensekey',
            unique_together=set(),
        ),
        migrations.CreateModel(
            name='HikConfigurationDb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('middleware_url', models.CharField(max_length=255)),
                ('middleware_port', models.CharField(max_length=11)),
                ('device_ip', models.CharField(max_length=255)),
                ('device_port', models.CharField(max_length=11)),
                ('device_username', models.CharField(max_length=255)),
                ('device_password', models.CharField(max_length=255)),
                ('gym', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hik_configuration', to='home.gymoffice')),
                ('gym_branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hik_configuration', to='home.gymbranch')),
            ],
        ),
    ]
