# Generated by Django 6.0.1 on 2026-04-13 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_licensekey_unique_together_hikconfigurationdb'),
    ]

    operations = [
        migrations.AddField(
            model_name='gymoffice',
            name='currency_code',
            field=models.CharField(default='INR', help_text='e.g. INR, USD, AED, EUR', max_length=10),
        ),
        migrations.AddField(
            model_name='gymoffice',
            name='currency_symbol',
            field=models.CharField(default='₹', help_text='e.g. ₹, $, AED, €', max_length=10),
        ),
    ]
