# Generated by Django 6.0.1 on 2026-04-29 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0006_gymoffice_currency_code_gymoffice_currency_symbol"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Super Admin"),
                    ("gym_admin", "Gym Owner/Admin"),
                    ("branch_admin", "Branch Manager"),
                    ("staff", "Staff"),
                    ("trainer", "Trainer"),
                    ("member", "Gym Member"),
                ],
                max_length=20,
            ),
        ),
    ]
