# Generated by Django 5.2.4 on 2026-01-15 07:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0005_alter_licensekey_unique_together_hikconfigurationdb'),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch_DB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_name', models.CharField(choices=[('Morning', 'Morning'), ('Evening', 'Evening'), ('Night', 'Night')], max_length=255)),
                ('batch_status', models.BooleanField(default=True)),
                ('batch_time', models.TimeField()),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='home.gymoffice')),
            ],
            options={
                'verbose_name': 'Batch',
                'verbose_name_plural': 'Batches',
                'unique_together': {('gym', 'batch_name', 'batch_time')},
            },
        ),
        migrations.CreateModel(
            name='SubscriptionPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.PositiveIntegerField()),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_periods', to='home.gymoffice')),
            ],
            options={
                'unique_together': {('gym', 'period')},
            },
        ),
        migrations.CreateModel(
            name='TypeSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_types', to='home.gymoffice')),
            ],
            options={
                'unique_together': {('gym', 'name')},
            },
        ),
    ]
