# Generated by Django 5.2.4 on 2026-01-15 10:02

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0005_alter_licensekey_unique_together_hikconfigurationdb'),
        ('utils', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_id', models.CharField(editable=False, max_length=50, unique=True)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=20)),
                ('mobile_number', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.TextField(blank=True, max_length=500, null=True)),
                ('height', models.DecimalField(blank=True, decimal_places=2, help_text='Height in cm', max_digits=5, null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, help_text='Weight in kg', max_digits=5, null=True)),
                ('blood_group', models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=10, null=True)),
                ('medical_history', models.TextField(blank=True, max_length=2000, null=True)),
                ('emergency_contact_name', models.CharField(blank=True, max_length=255, null=True)),
                ('emergency_contact_number', models.CharField(blank=True, max_length=20, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='members/photos/')),
                ('id_proof', models.FileField(blank=True, null=True, upload_to='members/id_proofs/')),
                ('registration_date', models.DateField(default=django.utils.timezone.now)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True, help_text='Overall account status (can be disabled by admin)')),
                ('membership_status', models.CharField(choices=[('Active', 'Active'), ('Expired', 'Expired'), ('Suspended', 'Suspended'), ('Cancelled', 'Cancelled')], default='Active', max_length=20)),
                ('access_enabled', models.BooleanField(default=False, help_text='Can access gym (based on valid subscription + payment)')),
                ('access_token', models.CharField(blank=True, help_text='RFID/Barcode/QR for gate access', max_length=255, null=True, unique=True)),
                ('notes', models.TextField(blank=True, help_text='Admin notes about member', null=True)),
                ('branch', models.ForeignKey(blank=True, help_text='Primary branch', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='home.gymbranch')),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='home.gymoffice')),
            ],
            options={
                'ordering': ['-date_added'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.PositiveIntegerField(help_text='Number of days/weeks/months')),
                ('duration_unit', models.CharField(choices=[('Days', 'Days'), ('Weeks', 'Weeks'), ('Months', 'Months'), ('Years', 'Years')], default='Months', max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch_flexible', models.BooleanField(default=False, help_text='Member can attend any batch')),
                ('base_amount', models.DecimalField(decimal_places=2, help_text='Base subscription amount', max_digits=10)),
                ('discount_percentage', models.DecimalField(decimal_places=2, default=0, help_text='Discount percentage', max_digits=5)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, help_text='Fixed discount amount', max_digits=10)),
                ('final_amount', models.DecimalField(decimal_places=2, help_text='Final amount after discounts', max_digits=10)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('includes_personal_training', models.BooleanField(default=False)),
                ('personal_training_sessions', models.PositiveIntegerField(default=0, help_text='Number of PT sessions included')),
                ('includes_diet_plan', models.BooleanField(default=False)),
                ('includes_locker', models.BooleanField(default=False)),
                ('locker_number', models.CharField(blank=True, max_length=50, null=True)),
                ('freeze_allowed', models.BooleanField(default=False)),
                ('freeze_days_allowed', models.PositiveIntegerField(default=0, help_text='Number of days member can freeze subscription')),
                ('freeze_days_used', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Expired', 'Expired'), ('Cancelled', 'Cancelled'), ('Suspended', 'Suspended'), ('Frozen', 'Frozen')], default='Active', max_length=20)),
                ('is_fully_paid', models.BooleanField(default=False)),
                ('payment_terms', models.CharField(choices=[('Full', 'Full Payment'), ('Installment', 'Installment'), ('Monthly', 'Monthly')], default='Full', max_length=50)),
                ('installment_count', models.PositiveIntegerField(default=1, help_text='Number of installments if applicable')),
                ('custom_terms', models.TextField(blank=True, help_text='Custom terms and conditions for this subscription', null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.TextField(blank=True, null=True)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscriptions', to='utils.batch_db')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='members.member')),
                ('subscription_type', models.ForeignKey(blank=True, help_text='Type of subscription (optional category)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='utils.typesubscription')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SubscriptionFreeze',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('freeze_start_date', models.DateField()),
                ('freeze_end_date', models.DateField()),
                ('days_frozen', models.PositiveIntegerField()),
                ('reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('unfrozen_at', models.DateTimeField(blank=True, null=True)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='freeze_logs', to='members.subscription')),
            ],
            options={
                'ordering': ['-freeze_start_date'],
            },
        ),
        migrations.AddIndex(
            model_name='member',
            index=models.Index(fields=['gym', 'member_id'], name='members_mem_gym_id_90f1f8_idx'),
        ),
        migrations.AddIndex(
            model_name='member',
            index=models.Index(fields=['gym', 'mobile_number'], name='members_mem_gym_id_c48be7_idx'),
        ),
        migrations.AddIndex(
            model_name='member',
            index=models.Index(fields=['access_token'], name='members_mem_access__6cebea_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='member',
            unique_together={('gym', 'mobile_number')},
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['member', 'status'], name='members_sub_member__5333a7_idx'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['start_date', 'end_date'], name='members_sub_start_d_7dcee6_idx'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['status', 'end_date'], name='members_sub_status_a901b1_idx'),
        ),
    ]
