# Generated by Django 6.0.1 on 2026-04-06 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0002_subscriptioninstallment"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscription",
            name="balance_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
