# Generated by Django 6.0.1 on 2026-04-06 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0003_subscription_balance_amount"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscriptioninstallment",
            name="amount_paid",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Amount paid for this specific installment",
                max_digits=10,
            ),
        ),
        migrations.AlterField(
            model_name="subscriptioninstallment",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Partially Paid", "Partially Paid"),
                    ("Paid", "Paid"),
                    ("Overdue", "Overdue"),
                ],
                default="Pending",
                max_length=20,
            ),
        ),
    ]
