# Generated by Django 6.0.1 on 2026-04-07 06:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0005_alter_licensekey_unique_together_hikconfigurationdb"),
        ("members", "0004_subscriptioninstallment_amount_paid_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="access_expiry_date",
            field=models.DateField(
                blank=True,
                help_text="Highest access date across all active/paid subscriptions",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="subscription",
            name="access_branch",
            field=models.ForeignKey(
                blank=True,
                help_text="Branch where this subscription grants access (None for HQ/All)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="branch_subscriptions",
                to="home.gymbranch",
            ),
        ),
        migrations.AddField(
            model_name="subscription",
            name="is_hq_access",
            field=models.BooleanField(
                default=False, help_text="Grants access to headquarters/all branches"
            ),
        ),
    ]
