# Generated by Django 6.0.1 on 2026-04-07 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "members",
            "0005_member_access_expiry_date_subscription_access_branch_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="is_access_blocked",
            field=models.BooleanField(
                default=False,
                help_text="Manually block access regardless of subscription status",
            ),
        ),
        migrations.AddField(
            model_name="member",
            name="manual_access_expiry",
            field=models.DateField(
                blank=True, help_text="Manual access extension date", null=True
            ),
        ),
        migrations.AlterField(
            model_name="member",
            name="access_expiry_date",
            field=models.DateField(
                blank=True,
                help_text="Highest access date across all active/paid subscriptions (or manual extension)",
                null=True,
            ),
        ),
    ]
