# Generated by Django 6.0.1 on 2026-04-07 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "members",
            "0006_member_is_access_blocked_member_manual_access_expiry_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscription",
            name="duration_unit",
            field=models.CharField(
                choices=[
                    ("Days", "Days"),
                    ("Weeks", "Weeks"),
                    ("Months", "Months"),
                    ("Years", "Years"),
                ],
                default="Days",
                max_length=20,
            ),
        ),
    ]
