# Generated by Django 6.0.1 on 2026-04-07 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0007_alter_subscription_duration_unit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscription",
            name="end_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
