# Generated by Django 6.0.1 on 2026-04-08 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0008_alter_subscription_end_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscription",
            name="installment_period",
            field=models.PositiveIntegerField(
                default=1, help_text="Frequency of installments (e.g., 1, 2)"
            ),
        ),
        migrations.AddField(
            model_name="subscription",
            name="installment_period_unit",
            field=models.CharField(
                choices=[
                    ("Days", "Days"),
                    ("Weeks", "Weeks"),
                    ("Months", "Months"),
                    ("Years", "Years"),
                ],
                default="Months",
                help_text="Unit for installment frequency",
                max_length=20,
            ),
        ),
    ]
