# Generated by Django 6.0.1 on 2026-04-10 04:23

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0009_subscription_installment_period_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="risk_medical",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="HealthHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("emergency_contact_name", models.CharField(max_length=255)),
                ("emergency_contact_relationship", models.CharField(max_length=100)),
                ("emergency_contact_phone", models.CharField(max_length=20)),
                (
                    "emergency_contact_address",
                    models.TextField(blank=True, max_length=500, null=True),
                ),
                (
                    "current_weight",
                    models.FloatField(
                        validators=[django.core.validators.MinValueValidator(0)]
                    ),
                ),
                (
                    "current_height",
                    models.FloatField(
                        validators=[django.core.validators.MinValueValidator(0)]
                    ),
                ),
                (
                    "fitness_goal",
                    models.CharField(
                        choices=[
                            ("weight_loss", "Weight Loss"),
                            ("weight_gain", "Weight Gain"),
                            ("muscle_building", "Muscle Building"),
                            ("cardiovascular", "Cardiovascular Fitness"),
                            ("strength", "Strength Training"),
                            ("flexibility", "Flexibility & Mobility"),
                            ("sports_specific", "Sports Specific Training"),
                            ("general_fitness", "General Fitness"),
                            ("rehabilitation", "Rehabilitation"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "fitness_goal_details",
                    models.TextField(blank=True, max_length=500, null=True),
                ),
                (
                    "pt_availability",
                    models.CharField(
                        choices=[
                            ("morning", "Morning (6 AM - 12 PM)"),
                            ("afternoon", "Afternoon (12 PM - 6 PM)"),
                            ("evening", "Evening (6 PM - 10 PM)"),
                            ("flexible", "Flexible"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "preferred_days",
                    models.CharField(
                        help_text="e.g., Monday, Wednesday, Friday", max_length=200
                    ),
                ),
                (
                    "physician_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "physician_phone",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("under_medical_care", models.BooleanField(default=False)),
                (
                    "medical_care_reason",
                    models.TextField(blank=True, max_length=500, null=True),
                ),
                ("taking_medications", models.BooleanField(default=False)),
                ("allergies", models.TextField(blank=True, max_length=1000, null=True)),
                ("high_blood_pressure", models.BooleanField(default=False)),
                ("bone_joint_problems", models.BooleanField(default=False)),
                ("over_65", models.BooleanField(default=False)),
                ("unaccustomed_exercise", models.BooleanField(default=False)),
                ("family_asthma", models.BooleanField(default=False)),
                (
                    "personal_asthma",
                    models.TextField(blank=True, max_length=500, null=True),
                ),
                ("family_respiratory", models.BooleanField(default=False)),
                (
                    "personal_respiratory",
                    models.TextField(blank=True, max_length=500, null=True),
                ),
                ("family_diabetes", models.BooleanField(default=False)),
                (
                    "personal_diabetes_type1",
                    models.TextField(blank=True, max_length=200, null=True),
                ),
                (
                    "personal_diabetes_type2",
                    models.TextField(blank=True, max_length=200, null=True),
                ),
                (
                    "diabetes_duration",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("family_epilepsy", models.BooleanField(default=False)),
                (
                    "personal_epilepsy_petite",
                    models.TextField(blank=True, max_length=200, null=True),
                ),
                (
                    "personal_epilepsy_grand",
                    models.TextField(blank=True, max_length=200, null=True),
                ),
                (
                    "personal_epilepsy_other",
                    models.TextField(blank=True, max_length=200, null=True),
                ),
                ("family_osteoporosis", models.BooleanField(default=False)),
                (
                    "personal_osteoporosis",
                    models.TextField(blank=True, max_length=500, null=True),
                ),
                (
                    "occupational_stress",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                        ],
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "energy_level",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                        ],
                        max_length=10,
                        null=True,
                    ),
                ),
                ("caffeine_daily", models.IntegerField(blank=True, null=True)),
                ("alcohol_weekly", models.IntegerField(blank=True, null=True)),
                ("colds_per_year", models.IntegerField(blank=True, null=True)),
                ("anemia", models.TextField(blank=True, max_length=300, null=True)),
                (
                    "gastrointestinal_disorder",
                    models.TextField(blank=True, max_length=500, null=True),
                ),
                (
                    "hypoglycemia",
                    models.TextField(blank=True, max_length=300, null=True),
                ),
                (
                    "thyroid_disorder",
                    models.TextField(blank=True, max_length=300, null=True),
                ),
                (
                    "prenatal_postnatal",
                    models.TextField(blank=True, max_length=300, null=True),
                ),
                (
                    "high_bp_details",
                    models.TextField(blank=True, max_length=300, null=True),
                ),
                (
                    "hypertension_details",
                    models.TextField(blank=True, max_length=300, null=True),
                ),
                (
                    "high_cholesterol",
                    models.TextField(blank=True, max_length=500, null=True),
                ),
                (
                    "hyperlipidemia",
                    models.TextField(blank=True, max_length=500, null=True),
                ),
                (
                    "heart_disease",
                    models.TextField(blank=True, max_length=500, null=True),
                ),
                (
                    "heart_attack",
                    models.TextField(blank=True, max_length=300, null=True),
                ),
                ("stroke", models.TextField(blank=True, max_length=300, null=True)),
                ("angina", models.TextField(blank=True, max_length=300, null=True)),
                ("gout", models.TextField(blank=True, max_length=300, null=True)),
                ("exercise_restrictions", models.BooleanField(default=False)),
                (
                    "exercise_restrictions_details",
                    models.TextField(blank=True, max_length=1000, null=True),
                ),
                ("chest_pain_exercise", models.BooleanField(default=False)),
                (
                    "chest_pain_details",
                    models.TextField(blank=True, max_length=500, null=True),
                ),
                (
                    "smoking_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("non_user", "Non-user or former user"),
                            ("cigar_pipe", "Cigar and/or pipe"),
                            ("1_15", "15 or less cigarettes per day"),
                            ("16_25", "16 to 25 cigarettes per day"),
                            ("26_35", "26 to 35 cigarettes per day"),
                            ("35_plus", "More than 35 cigarettes per day"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("smoking_quit_date", models.DateField(blank=True, null=True)),
                (
                    "head_neck_issues",
                    models.TextField(blank=True, max_length=500, null=True),
                ),
                (
                    "upper_back_issues",
                    models.TextField(blank=True, max_length=500, null=True),
                ),
                (
                    "shoulder_clavicle_issues",
                    models.TextField(blank=True, max_length=500, null=True),
                ),
                (
                    "arm_elbow_issues",
                    models.TextField(blank=True, max_length=500, null=True),
                ),
                (
                    "wrist_hand_issues",
                    models.TextField(blank=True, max_length=500, null=True),
                ),
                (
                    "lower_back_issues",
                    models.TextField(blank=True, max_length=500, null=True),
                ),
                (
                    "hip_pelvis_issues",
                    models.TextField(blank=True, max_length=500, null=True),
                ),
                (
                    "thigh_knee_issues",
                    models.TextField(blank=True, max_length=500, null=True),
                ),
                (
                    "arthritis_details",
                    models.TextField(blank=True, max_length=500, null=True),
                ),
                (
                    "hernia_details",
                    models.TextField(blank=True, max_length=300, null=True),
                ),
                (
                    "surgeries_details",
                    models.TextField(blank=True, max_length=1000, null=True),
                ),
                (
                    "other_musculoskeletal",
                    models.TextField(blank=True, max_length=500, null=True),
                ),
                ("on_diet_plan", models.BooleanField(default=False)),
                (
                    "diet_plan_details",
                    models.TextField(blank=True, max_length=500, null=True),
                ),
                ("taking_supplements", models.BooleanField(default=False)),
                (
                    "supplements_list",
                    models.TextField(blank=True, max_length=500, null=True),
                ),
                ("weight_fluctuations", models.BooleanField(default=False)),
                ("recent_weight_change", models.BooleanField(default=False)),
                (
                    "weight_change_amount",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "weight_change_duration",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "caffeine_beverages_daily",
                    models.IntegerField(blank=True, null=True),
                ),
                (
                    "nutritional_habits_description",
                    models.TextField(blank=True, max_length=1000, null=True),
                ),
                (
                    "food_allergies_issues",
                    models.TextField(blank=True, max_length=500, null=True),
                ),
                (
                    "work_exercise_habits",
                    models.CharField(
                        blank=True,
                        choices=[
                            (
                                "intense_both",
                                "Intense occupational and recreational exertion",
                            ),
                            (
                                "moderate_both",
                                "Moderate occupational and recreational exertion",
                            ),
                            (
                                "sedentary_intense",
                                "Sedentary occupational and intense recreational exertion",
                            ),
                            (
                                "sedentary_moderate",
                                "Sedentary occupational and moderate recreational exertion",
                            ),
                            (
                                "sedentary_light",
                                "Sedentary occupational and light recreational exertion",
                            ),
                            ("no_exertion", "Complete lack of all exertion"),
                        ],
                        max_length=30,
                        null=True,
                    ),
                ),
                (
                    "work_stress_level",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("minimal", "Minimal"),
                            ("moderate", "Moderate"),
                            ("average", "Average"),
                            ("extremely", "Extremely"),
                        ],
                        max_length=15,
                        null=True,
                    ),
                ),
                (
                    "home_stress_level",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("minimal", "Minimal"),
                            ("moderate", "Moderate"),
                            ("average", "Average"),
                            ("extremely", "Extremely"),
                        ],
                        max_length=15,
                        null=True,
                    ),
                ),
                ("works_over_40_hours", models.BooleanField(default=False)),
                (
                    "additional_comments",
                    models.TextField(blank=True, max_length=2000, null=True),
                ),
                (
                    "has_risky_heart_conditions",
                    models.BooleanField(
                        default=False,
                        help_text="Heart disease, uncontrolled high blood pressure, irregular heartbeat, history of heart attack/stroke",
                    ),
                ),
                (
                    "risky_heart_conditions_details",
                    models.TextField(
                        blank=True,
                        help_text="Explain specific heart/cardiovascular conditions",
                        max_length=1000,
                        null=True,
                    ),
                ),
                (
                    "has_risky_health_conditions",
                    models.BooleanField(
                        default=False,
                        help_text="Respiratory issues, joint problems, metabolic conditions, neurological disorders, etc.",
                    ),
                ),
                (
                    "risky_health_conditions_details",
                    models.TextField(
                        blank=True,
                        help_text="Explain specific health conditions that may be risky for gym workouts",
                        max_length=1000,
                        null=True,
                    ),
                ),
                ("date_completed", models.DateTimeField(auto_now_add=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "member",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="health_history",
                        to="members.member",
                    ),
                ),
            ],
            options={
                "verbose_name": "Health History",
                "verbose_name_plural": "Health Histories",
            },
        ),
        migrations.CreateModel(
            name="Medication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("medication_type", models.CharField(max_length=255)),
                ("dosage_frequency", models.CharField(max_length=255)),
                ("reason_for_taking", models.CharField(max_length=500)),
                (
                    "health_history",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="medications",
                        to="members.healthhistory",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ParqForm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "emergency_contact_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "emergency_contact_phone",
                    models.CharField(blank=True, max_length=15, null=True),
                ),
                (
                    "emergency_contact_mobile",
                    models.CharField(blank=True, max_length=15, null=True),
                ),
                (
                    "heart_condition",
                    models.BooleanField(
                        default=False,
                        help_text="Has your doctor ever said that you have a heart condition?",
                    ),
                ),
                (
                    "chest_pain_activity",
                    models.BooleanField(
                        default=False,
                        help_text="Do you have chest pain brought on by physical activity?",
                    ),
                ),
                (
                    "chest_pain_last_month",
                    models.BooleanField(
                        default=False,
                        help_text="Have you developed chest pain in the last month?",
                    ),
                ),
                (
                    "lose_consciousness",
                    models.BooleanField(
                        default=False,
                        help_text="Do you tend to lose consciousness or fall over as a result of dizziness?",
                    ),
                ),
                (
                    "bone_joint_problem",
                    models.BooleanField(
                        default=False,
                        help_text="Do you have a bone or joint problem that could be aggravated by physical activity?",
                    ),
                ),
                (
                    "medical_conditions",
                    models.BooleanField(
                        default=False,
                        help_text="Do you suffer from asthma, diabetes, high blood pressure, epilepsy or a heart condition?",
                    ),
                ),
                (
                    "medical_conditions_specify",
                    models.TextField(
                        blank=True,
                        help_text="Please specify medical conditions",
                        null=True,
                    ),
                ),
                (
                    "current_treatment",
                    models.BooleanField(
                        default=False,
                        help_text="Do you have any current conditions or injuries being treated by a doctor?",
                    ),
                ),
                (
                    "current_treatment_specify",
                    models.TextField(
                        blank=True,
                        help_text="Please specify current treatment",
                        null=True,
                    ),
                ),
                (
                    "other_reason",
                    models.BooleanField(
                        default=False,
                        help_text="Do you know of any other reason why you should not take part in exercise?",
                    ),
                ),
                (
                    "other_reason_specify",
                    models.TextField(
                        blank=True, help_text="Please specify other reasons", null=True
                    ),
                ),
                (
                    "participant_signature",
                    models.TextField(
                        blank=True,
                        help_text="Participant signature data (base64)",
                        null=True,
                    ),
                ),
                (
                    "parent_guardian_signature",
                    models.TextField(
                        blank=True,
                        help_text="Parent/Guardian signature data (base64)",
                        null=True,
                    ),
                ),
                (
                    "tutor_signature",
                    models.TextField(
                        blank=True, help_text="Tutor signature data (base64)", null=True
                    ),
                ),
                ("form_date", models.DateField(auto_now_add=True)),
                ("participant_signature_date", models.DateField(blank=True, null=True)),
                (
                    "parent_guardian_signature_date",
                    models.DateField(blank=True, null=True),
                ),
                ("tutor_signature_date", models.DateField(blank=True, null=True)),
                ("requires_doctor_consent", models.BooleanField(default=False)),
                ("is_completed", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "member",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="health_history_parque",
                        to="members.member",
                    ),
                ),
            ],
            options={
                "verbose_name": "PAR-Q Form",
                "verbose_name_plural": "PAR-Q Forms",
            },
        ),
    ]
