# Generated by Django 6.0.1 on 2026-04-10 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0010_member_risk_medical_healthhistory_medication_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='public_token',
            field=models.UUIDField(blank=True, editable=False, null=True),
        ),
    ]
