# Generated by Django 6.0.1 on 2026-04-10 07:06

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0011_member_public_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='public_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True, unique=True),
        ),
    ]
