# Generated by Django 6.0.1 on 2026-04-17 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0012_alter_member_public_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subscription',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
