# Generated by Django 6.0.1 on 2026-04-17 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0013_member_is_deleted_subscription_is_deleted"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscriptioninstallment",
            name="discount_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Discount amount applied to this specific installment",
                max_digits=10,
            ),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="discount_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Total discount applied via offers",
                max_digits=10,
            ),
        ),
        migrations.AlterField(
            model_name="subscriptioninstallment",
            name="amount_paid",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Cash amount paid for this specific installment",
                max_digits=10,
            ),
        ),
    ]
