# Generated by Django 6.0.1 on 2026-04-29 06:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0015_member_assigned_trainer"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="user",
            field=models.OneToOneField(
                blank=True,
                help_text="User account for member login",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="member_profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
